---
- name: set_facts | Setting Debian Facts
  set_fact:
    wordpress_apache2_log_dir: /var/log/apache2
    wordpress_apache2_web_group: www-data
    wordpress_apache2_web_owner: www-data
    wordpress_apache2_web_root: /var/www/html
  when: ansible_os_family == "Debian"
